- name: Use Collections
  hosts: all
  connection: httpapi
  gather_facts: no
  collections:
    - f5networks.f5_bigip

  tasks:
    - debug:
        msg: "{{ lookup('template', 'templates/firewall_policy.json.j2') }}"

    - name: Create policies
      bigip_as3_deploy:
        content: "{{ lookup('template', 'templates/firewall_policy.json.j2') }}"
