- name: Use Collections
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Create policies
      include_tasks: tasks/deploy-policy.yaml
      loop: "{{ policies }}"
      loop_control:
        loop_var: policy
