address_lists:
  anyone:
    - "0.0.0.0/0"
  ftpClients:
    - "10.1.1.50"
    - "192.168.0.100-192.168.0.200"
  server:
    - "10.1.20.100"

port_lists:
  httpsPort:
    - 443
  ftpPorts:
    - 20
    - 21

policies:
  - name: "f5_bigip_http_policy"
    rules:
      - name: rule-1
        description: Allow anyone to access HTTP VS
        protocol: tcp
        source:
          address_lists:
            - anyone
        destination:
          address_lists:
            - server
          port_lists:
            - httpsPort
        action: accept
      - name: rule-2
        description: Deny all other traffic
        action: drop
  - name: "f5_bigip_ftp_policy"
    rules:
      - name: rule-1
        description: Allow internal clients access to FTP VS
        protocol: tcp
        source:
          address_lists:
            - ftpClients
        destination:
          address_lists:
            - server
          port_lists:
            - ftpPorts
        action: accept
      - name: rule-2
        description: Deny all other traffic
        action: drop
